[general]
live_config_reload = true

[window]
startup_mode = "Maximized"
padding = { x = 10, y = 10 }
opacity = 0.8
blur = true

[scrolling]
history = 100000
multiplier = 5

[font]
size = 14

[selection]
save_to_clipboard = true
